### ISSUE TITLE
How to de-noise child resources?

### ISSUE THREAD

**Issue by thomasninane** [ottijp/az-deployment-denoise#12]
Hello,

Sometimes, a resources belong to a parent resources (e.g., an Azure Machine Learning compute instance, which is associated to an Azure Machine Learning workspace). I couldn't find a way to make this de-noising tool work on such cases (though it is working flawlessly on "regular" resources).

Here is an example (the `enableBatchPrivateLink` and `updateStatus` properties are noise and I'd like to get rid of them):
![image](https://github.com/user-attachments/assets/903f3340-d7ca-4bab-99ab-aa2ccc9fd58e)

I have tried to add the following lines to `az-deployment-denoise.json`, but to no avail (I replaced `{AML_WORKSPACE_NAME}` with the real name of the Azure Machine Learning workspace):
```json
{
  "providerNamespace": "Microsoft.MachineLearningServices",
  "resourceType": "workspaces/computes",
  "propertyPath": "properties.properties.enableBatchPrivateLink"
},
{
  "providerNamespace": "Microsoft.MachineLearningServices",
  "resourceType": "workspaces/{AML_WORKSPACE_NAME}/computes",
  "propertyPath": "properties.properties.enableBatchPrivateLink"
}
```

Do you know how de-noising these child resources can be done?

**Comment by ottijp** [comment]
@thomasninane 
Hi,

Thank you for reaching out.

This tool assumes and parses that the format of the resource ID as follows:

`/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}`

In your case, the `resourceType` and `resourceName` are parsed as:

* resourceType = `workspaces`
* resourceName = `{AML_WORKSPACE_NAME}/computes/{CHILD_RESOURCE_NAME}`

To achieve the expected behavior, you can use the following configuration to filter the output accordingly:

```json
{
  "providerNamespace": "Microsoft.MachineLearningServices",
  "resourceType": "workspaces",
  "resourceNameRegex": ".+/computes/.+"
  "propertyPath": "properties.properties.enableBatchPrivateLink"
}
```

If this configuration does not take effect, could you please share the output of the following command with any sensitive information masked?

```
az deployment group what-if --no-pretty-print
```

**Comment by thomasninane** [comment]
Hello @ottijp,

The provided code snippet works perfectly. Thanks a lot for the clear explanations and for your assistance on using this great tool.
